# Grunt aliases
---
# Create a zipped artifact from a fresh build
'artifact':
  - 'clean:artifact'
  - 'shell:composerInstallProduction'
  - 'copy:artifact'
  - 'compress:artifact'
  - 'shell:composerInstall'

'deploy:trunk':
  - 'update-version'
  - 'artifact'
  - 'wp_deploy:trunk'

'deploy:master':
  - 'update-version'
  - 'artifact'
  - 'wp_deploy:master'
