# Grunt aliases
---
# Create a zipped artifact from a fresh build
'artifact':
  - 'clean:artifact'
  - 'shell:composer-install-production'
  - 'copy:artifact'
  - 'compress:artifact'
  - 'shell:composer-install-dev'

'deploy:trunk':
  - 'update-version'
  - 'artifact'
  - 'wp_deploy:trunk'

'deploy:master':
  - 'update-version'
  - 'artifact'
  - 'wp_deploy:master'
