os: linux
language: php

branches:
  only:
    - master
    - develop
    # Also build tags like 1.1.1 or 1.1 for deployment.
    - /(\d+\.)?(\d+\.)?(\*|\d+)/

jobs:
  fast_finish: true
  include:
    - php: 7.4
      env: PHPLINT=1 SECURITY=1
    - php: 5.6
      env: PHPLINT=1
    - php: 8.0
      env: PHPLINT=1
    - stage: deploy
      if: tag IS present
      before_deploy:
        - nvm install node
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH
        - yarn global add grunt-cli
        - yarn install
        - grunt set-version -new-version=$TRAVIS_TAG
        - grunt update-version
        - grunt artifact
        - openssl aes-256-cbc -K $encrypted_8f6358b271ea_key -iv $encrypted_8f6358b271ea_iv -in ./deploy_keys/travis_dist_id_rsa.enc -out ./deploy_keys/travis_dist_id_rsa -d
        - chmod 600 ./deploy_keys/travis_dist_id_rsa
        - eval $(ssh-agent -s)
        - ssh-add ./deploy_keys/travis_dist_id_rsa

       # If the commit was tagged, create an artifact and push it to the distribution github
      deploy:
        skip_cleanup: true
        provider: script
        script: bash scripts/deploy_to_dist.sh $TRAVIS_TAG yoast-test-helper
        on:
          tags: true
          repo: $TRAVIS_REPO_SLUG
          all_branches: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
- if [[ "$COVERAGE" != "1" ]]; then phpenv config-rm xdebug.ini || echo 'No xdebug config.'; fi
- export SECURITYCHECK_DIR=/tmp/security-checker

install:
- |
  if [[ "$PHPLINT" == "1" ]]; then
    composer install --no-interaction
  fi
- if [[ "$SECURITY" == "1" ]]; then wget -P $SECURITYCHECK_DIR https://github.com/fabpot/local-php-security-checker/releases/download/v1.2.0/local-php-security-checker_1.2.0_linux_amd64 && chmod +x $SECURITYCHECK_DIR/local-php-security-checker_1.2.0_linux_amd64;fi

before_script:
- export -f travis_fold
- export -f travis_time_start
- export -f travis_time_finish
- mysql --version
- phpenv versions
- php --version
- php -m
- curl --version
- git --version
- svn --version
- locale -a
- echo "repo $TRAVIS_REPO_SLUG commit $TRAVIS_COMMIT containing tag $TRAVIS_TAG"

script:
# PHP Linting
- |
  if [[ "$PHPLINT" == "1" ]]; then
    composer lint
  fi

# Check for known security vulnerabilities in the currently locked-in dependencies.
- if [[ "$SECURITY" == "1" ]]; then $SECURITYCHECK_DIR/local-php-security-checker_1.2.0_linux_amd64 --path=$(pwd)/composer.lock;fi
